"""empty message

Revision ID: 3da401581214
Revises: bfc9b22c58c4
Create Date: 2020-10-20 21:26:45.779003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3da401581214'
down_revision = 'bfc9b22c58c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('developer_skill', 'developer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('developer_skill', 'vacancy_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('developer_skill', 'vacancy_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('developer_skill', 'developer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
