"""empty message

Revision ID: ecfd2e07b34c
Revises: 3da401581214
Create Date: 2020-10-20 21:30:06.776648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecfd2e07b34c'
down_revision = '3da401581214'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('developer_skill', sa.Column('skill_id', sa.Integer(), nullable=False))
    op.drop_constraint('developer_skill_vacancy_id_fkey', 'developer_skill', type_='foreignkey')
    op.create_foreign_key(None, 'developer_skill', 'skill', ['skill_id'], ['id'])
    op.drop_column('developer_skill', 'vacancy_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('developer_skill', sa.Column('vacancy_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'developer_skill', type_='foreignkey')
    op.create_foreign_key('developer_skill_vacancy_id_fkey', 'developer_skill', 'vacancy', ['vacancy_id'], ['id'])
    op.drop_column('developer_skill', 'skill_id')
    # ### end Alembic commands ###
